### ISSUE TITLE
Creating a repository from a template is not enabled 

### ISSUE THREAD

**Issue by apherio** [strapi/strapi-starter-next-ecommerce#9]
**Problem :** 

![image](https://user-images.githubusercontent.com/3753897/106968234-b6f8d880-6748-11eb-86cd-2ff2c91e5d0c.png)

As mentioned in the Readme anyone cannot generate a new repository with the same directory structure and files as an existing repository as it's not enabled at the moment. 

**Possible Solution:**

Anyone with admin permissions to a repository can make the repository a template.
Enabling the [Select Template repository options](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) would solve this problem.

**Comment by remidej** [comment]
Thanks, it should work now
